---
title: "Class 6 R Function"
author: "Reina Bassil"
date: "10/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is a H1
This is my class 6 work. This will be **bold**

## A H2

### A level 3 heading H3

```{r}
plot(1:10)
```


```{r}
test1 <- read.table("test1.txt", header = TRUE, sep=",")
```

```{r}
text1
```
```{r}
test2 <- read.table("test2.txt", header= TRUE, sep= "$")
test2
```


```{r}
test3 <- read.table("test3.txt", header = FALSE, sep= "")
test3
```


```{r}
add <- function(x, y=1) {
    # Sum the input x and y
    x + y 
}
```

```{r}
add( c(5,6, 1, 5, 10), y=100)
```

```{r}
add( c(5, 5, NA, 7))
```

```{r}
x <- range( c(5,2,7,10))
x[1] #min value
x[2] #max value
```

```{r}
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
```

```{r}
rescale(c(1, 2, NA, 5))
```

```{r}
x <- c(1, 2, NA, 5)
range(x, na.rm = TRUE )
```

```{r}
rescale2 <- function(x) {
 rng <-range(x, na.rm= TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}
```


```{r}
rescale2( c(1,2,NA,5))
```

```{r}
recale2( c(1,10,”string”) )
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 if(na.rm) {
 rng <-range(x, na.rm=na.rm)
 } else {
 rng <-range(x)
 }
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 return(answer)
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 print("I can see it in ...")
return(answer)
}
```

```{r}
rescale3(1:10, plot= TRUE)
```


```{r}
library(bio3d)
```

```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

